name: Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2

      - name: Install deps
        run: deno install

      - name: Build project
        run: deno task build

      - name: Clear caches and dependencies
        run: |
          echo "Clearing previous build artifacts and caches..."
          rm -rf .cache node_modules deno.lock

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: dist/
